
import java.sql.*;
import guiproject.GUI.connect.*;
import java.util.Random;
import javax.swing.JOptionPane;
public class ApplicationForm extends javax.swing.JFrame {
Random rand= new Random();
int ran=rand.nextInt(311227);
Connection con=null;
Fields fd = new Fields();           
    public ApplicationForm() {
      initComponents();
     con=GetConnection.connectdb();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_dateofbirth = new javax.swing.JTextField();
        txt_localgovernment = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_occupation = new javax.swing.JTextField();
        SUBMIT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Accno = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        btn_delete = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SEARCH");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setText("DATE OF BIRTH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 66, 96, 32);

        jLabel2.setText("EMAIL ADDRESSEE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 104, 96, 32);

        jLabel3.setText("OCCUPATION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 220, 96, 40);

        jLabel4.setText("LOCAL GOVERNMENT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 144, 110, 32);

        jLabel5.setText("NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 180, 120, 32);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(150, 110, 161, 30);

        txt_dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateofbirthActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dateofbirth);
        txt_dateofbirth.setBounds(150, 70, 161, 30);
        jPanel1.add(txt_localgovernment);
        txt_localgovernment.setBounds(150, 150, 161, 30);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name);
        txt_name.setBounds(150, 190, 161, 30);
        jPanel1.add(txt_occupation);
        txt_occupation.setBounds(150, 230, 161, 30);

        SUBMIT.setText("SUBMIT");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        jPanel1.add(SUBMIT);
        SUBMIT.setBounds(290, 270, 80, 23);

        jLabel6.setText("WELCOME TO FIRSTBANK PLC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, -6, 160, 40);
        jPanel1.add(Accno);
        Accno.setBounds(220, 30, 129, 30);

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(20, 30, 90, 30);

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH);
        SEARCH.setBounds(110, 30, 73, 30);

        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(10, 270, 80, 30);

        deletebutton.setText("delete!");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton);
        deletebutton.setBounds(90, 270, 67, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateofbirthActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    Accno.setText("0044"+ran);
    }//GEN-LAST:event_formWindowActivated

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
    fd.Account_number=Accno.getText();
    fd.Date_of_birth=txt_dateofbirth.getText();
    fd.Email=txt_email.getText();
    fd.Local_Government=txt_localgovernment.getText();
    fd.Name=txt_name.getText();
    fd.Occupation=txt_occupation.getText();
    try{
   String query=("insert into atm(ACCOUNTNUMBER,NAME,DATE_OF_BIRTH,EMAIL,LOCAL_GOVERNMENT,OCCUPATION) Values(?,?,?,?,?,?)");     
        fd.pt=con.prepareStatement(query);
        fd.pt.setString(1,fd.Account_number);
        fd.pt.setString(2,fd.Name);
        fd.pt.setString(3,fd.Date_of_birth);
        fd.pt.setString(4,fd.Email);
        fd.pt.setString(5,fd.Local_Government);
        fd.pt.setString(6,fd.Occupation);
        fd.pt.execute();
        JOptionPane.showConfirmDialog(null, "enter YES to save record");
        JOptionPane.showMessageDialog(null, "record saved");
        con.close();
         Accno.setText("");
        txt_dateofbirth.setText("");
        txt_email.setText("");
        txt_localgovernment.setText("");
        txt_name.setText("");
        txt_occupation.setText("");
      
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_SUBMITActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
      
          
          
    }//GEN-LAST:event_txt_searchActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
     try{
            String sql=("SELECT * from atm where ACCOUNTNUMBER="+txt_search.getText()+" ");
        fd.pt=con.prepareStatement(sql);
        fd.RS=fd.pt.executeQuery();
        while(fd.RS.next()){
       // Accno.setText(fd.RS.getString("ACCOUNTNUMBER"));
        txt_dateofbirth.setText(fd.RS.getString("DATE_OF_BIRTH"));
        txt_email.setText(fd.RS.getString("EMAIL"));
        txt_localgovernment.setText(fd.RS.getString("LOCAL_GOVERNMENT"));
        txt_name.setText(fd.RS.getString("NAME"));
        txt_occupation.setText(fd.RS.getString("OCCUPATION"));
             
            
            
            
        }
            
          
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
          
      }
    }//GEN-LAST:event_SEARCHActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        /*try{
            String delete=("DELETE from atm where ACCOUNTNUMBER="+txt_search.getText()+" ");
        fd.pt=con.prepareStatement(delete);
        fd.pt.executeUpdate();
       JOptionPane.showMessageDialog(null,"the record has been deleted succesfully");
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
          
      }*/
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        try{
            String delete=("DELETE from atm where DATE_OF_BIRTH="+btn_delete.getText()+" ");
        fd.pt=con.prepareStatement(delete);
        fd.pt.executeUpdate();
       JOptionPane.showMessageDialog(null,"the record has been deleted succesfully");
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
          
      }
        
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Accno;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JTextField btn_delete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JTextField txt_dateofbirth;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_localgovernment;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_occupation;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
